const std = @import("std");
const age = @import("age");
const clap = @import("clap");

const errors = @import("zage/errors.zig");
const utils = @import("zage/utils.zig");

const Error = errors.Error;

const usage_string =
    \\Usage:
    \\    zage [--encrypt] (-r RECIPIENT | -R PATH)... [-i IDENTITY | -j PLUGIN] [--armor] [-o OUTPUT] [INPUT]
    \\    zage [--encrypt] --passphrase [--armor] [-o OUTPUT] [INPUT]
    \\    zage --decrypt [-i IDENTITY | -j PLUGIN] [-o OUTPUT] [INPUT]
    \\
    \\Arguments:
    \\    [INPUT] Path of input file to read from (Default=stdin).
    \\
    \\Options:
    \\    -o, --output OUTPUT         Path of output file to write to (Default=stdout).
    \\    -v, --version               Print the version information and exit.
    \\    -h, --help                  Print this help message and exit.
    \\
    \\  Encryption options:
    \\    -e, --encrypt               Encrypt the input to the output (DEFAULT).
    \\    -r, --recipient RECIPIENT   Encrypt to the specified RECIPIENT. Can be repeated.
    \\    -R, --recipients-file PATH  Encrypt to the recipients listed at PATH. Can be repeated.
    \\    -p, --passphrase            Encrypt with a passphrase.
    \\    -a, --armor                 Encrypt to a PEM encoded format.
    \\    -i, --identity IDENTITY     Path to file of identities, encrypts the input using
    \\                                the corresponding recipients. Can be repeated.
    \\    -j PLUGIN                   Use age-plugin-PLUGIN as an identity
    \\
    \\  Decryption options:
    \\    -d, --decrypt               Decrypt the input to the output.
    \\    -i, --identity IDENTITY     Path to file of identities, used to decrypt. Can be repeated.
    \\    -j PLUGIN                   Use age-plugin-PLUGIN as an identity
    \\
    \\If OUTPUT exists, it will be overwritten.
    \\
    \\RECIPIENT can be:
    \\- An age public key, generated by zage-keygen ("age1...")
    \\- An SSH public key ("ssh-ed25519 AAAA...", "ssh-rsa AAAA...")
    \\
    \\PATH is a path to a file containing age recipients, one per line
    \\(ignoring "#" prefixed comments and empty lines). "-" may be used to
    \\read recipients from standard input.
    \\
    \\IDENTITY is a path to a file with age identities, one per line
    \\(ignoring "#" prefixed comments and empty lines), or to an SSH key file.
    \\Passphrase-encrypted age identity files can be used as identity files.
    \\Multiple identities may be provided, and any unused ones will be ignored.
    \\"-" may be used to read identities from standard input.
    \\
;

const params_string =
    \\-e, --encrypt                   Encrypt the input to the output (DEFAULT).
    \\-d, --decrypt                   Decrypt the input to the output.
    \\-o, --output <OUTPUT>           Path of output file to write to (Default=stdout).
    \\-r, --recipient <RECIPIENT>...  Encrypt to the specified RECIPIENT. Can be repeated.
    \\-R, --recipients-file <PATH>... Encrypt to the recipients listed at PATH. Can be repeated.
    \\-i, --identity <IDENTITY>...    Path to file of identities. Can be repeated.
    \\-p, --passphrase <PASSPHRASE>   Encrypt with a passphrase.
    \\-j <PLUGIN>                     Use age-plugin-PLUGIN as an identity
    \\-v, --version                   Print the version information and exit.
    \\-h, --help                      Print this help message and exit.
    \\<INPUT>                         Path of input file to read from (Default=stdin).
    \\
;

const parsers = .{
    .OUTPUT = clap.parsers.string,
    .RECIPIENT = clap.parsers.string,
    .PATH = clap.parsers.string,
    .IDENTITY = clap.parsers.string,
    .PASSPHRASE = clap.parsers.string,
    .PLUGIN = clap.parsers.string,
    .INPUT = clap.parsers.string,
};

const ZageArgs = struct {
    // encrypt or decrypt
    mode: Mode = .encrypt,
    // input file
    input: std.fs.File = std.fs.File.stdin(),
    // output file
    output: std.fs.File = std.fs.File.stdout(),
    // recipients - file? string? array of strings? or a custom data structure?
    recipients: []u8 = undefined,
    // identities - file? string? array of strings? or a custom data structure?
    identities: []u8 = undefined,
    // passphrase
    passphrase: []u8 = undefined,
    // max work effort - u16 enough? more?
    max_work_effort: u16 = 0,
    // plugin - separate? or do we append it to our identities?
    // do we accept the plugin flag and the identities flag in one call?
    plugin: []u8 = undefined,

    const Mode = enum {
        encrypt,
        decrypt,
    };
};

pub fn main() !void {
    const gpa = std.heap.page_allocator;

    var args = ZageArgs{};
    {
        var args_alloc = std.heap.ArenaAllocator.init(gpa);
        const allocator = args_alloc.allocator();
        defer args_alloc.deinit();

        const params = comptime clap.parseParamsComptime(params_string);

        var diag = clap.Diagnostic{};
        const res = clap.parse(clap.Help, &params, parsers, .{
            .diagnostic = &diag,
            .allocator = allocator,
        }) catch |err| {
            // try diag.reportToFile(.stderr(), err);
            switch (err) {
                Error.InvalidArgument => {
                    try utils.printErrorToStdout("Error: Invalid argument found\n", .{});
                },
                Error.DoesntTakeValue => {
                    try utils.printErrorToStdout("Error: Flag doesn't take a value\n", .{});
                },
                Error.MissingValue => {
                    try utils.printErrorToStdout("Error: Required value missing\n", .{});
                },
                else => {
                    try utils.printErrorToStdout("Error: No application memory available\n", .{});
                },
            }
            try utils.printToStdout(usage_string, .{});
            return;
        };

        if (res.args.help != 0) {
            try utils.printToStdout(usage_string, .{});
            return;
        }
        if (res.args.version != 0) {
            try utils.printToStdout("version: alpha neutron\n", .{});
            return;
        }

        if (res.args.encrypt != 0 and res.args.decrypt != 0) {
            try utils.printErrorToStdout("Error: -e/--encypt can't be used with -d/--decrypt\n", .{});
            return;
        }

        if (res.args.decrypt != 0) args.mode = .decrypt;

        const cwd = std.fs.cwd();

        if (res.args.output) |path| {
            args.output = cwd.createFile(path, .{}) catch {
                try utils.printErrorToStdout("Error: Unable to create output file {s}\n", .{path});
                return;
            };
        }
        for (res.args.recipient) |r| {
            std.debug.print("recipient: {s}\n", .{r});
        }
        for (res.args.@"recipients-file") |path| {
            // try cwd.openFile(path, .{});
            std.debug.print("recipient file: {s}\n", .{path});
        }
        for (res.args.identity) |path| {
            // try cwd.openFile(path, .{});
            std.debug.print("identity file: {s}\n", .{path});
        }
        if (res.args.passphrase) |pw| {
            std.debug.print("passphrase: {s}\n", .{pw});
        }
        if (res.args.j) |plugin| {
            std.debug.print("plugin: {s}\n", .{plugin});
        }
        if (res.positionals[0]) |input| {
            args.input = cwd.openFile(input, .{}) catch {
                try utils.printErrorToStdout("Error: Unable to open input file {s}\n", .{input});
                return;
            };
        }
    }
    std.debug.print("{}\n", .{args});
}

test {
    std.testing.refAllDeclsRecursive(@This());
}
