const std = @import("std");
const errors = @import("zage/errors.zig");
const age = @import("age");
const clap = @import("clap");

const usage_string =
    \\Usage:
    \\    zage [--encrypt] (-r RECIPIENT | -R PATH)... [-i IDENTITY | -j PLUGIN] [--armor] [-o OUTPUT] [INPUT]
    \\    zage [--encrypt] --passphrase [--armor] [-o OUTPUT] [INPUT]
    \\    zage --decrypt [-i IDENTITY | -j PLUGIN] [-o OUTPUT] [INPUT]
    \\
    \\Arguments:
    \\    [INPUT] Path of input file to read from (Default=stdin).
    \\
    \\Options:
    \\    -o, --output OUTPUT         Path of output file to write to (Default=stdout).
    \\    -v, --version               Print the version information and exit.
    \\    -h, --help                  Print this help message and exit.
    \\
    \\  Encryption options:
    \\    -e, --encrypt               Encrypt the input to the output (DEFAULT).
    \\    -r, --recipient RECIPIENT   Encrypt to the specified RECIPIENT. Can be repeated.
    \\    -R, --recipients-file PATH  Encrypt to the recipients listed at PATH. Can be repeated.
    \\    -p, --passphrase            Encrypt with a passphrase.
    \\    -a, --armor                 Encrypt to a PEM encoded format.
    \\    -i, --identity IDENTITY     Path to file of identities, encrypts the input using
    \\                                the corresponding recipients. Can be repeated.
    \\    -j PLUGIN                   Use age-plugin-PLUGIN as an identity
    \\
    \\  Decryption options:
    \\    -d, --decrypt               Decrypt the input to the output.
    \\    -i, --identity IDENTITY     Path to file of identities, used to decrypt. Can be repeated.
    \\    -j PLUGIN                   Use age-plugin-PLUGIN as an identity
    \\
    \\If OUTPUT exists, it will be overwritten.
    \\
    \\RECIPIENT can be:
    \\- An age public key, generated by zage-keygen ("age1...")
    \\- An SSH public key ("ssh-ed25519 AAAA...", "ssh-rsa AAAA...")
    \\
;

const params_string =
    \\-e, --encrypt                   Encrypt the input to the output (DEFAULT).
    \\-d, --decrypt                   Decrypt the input to the output.
    \\-o, --output <OUTPUT>           Path of output file to write to (Default=stdout).
    \\-r, --recipient <RECIPIENT>...  Encrypt to the specified RECIPIENT. Can be repeated.
    \\-R, --recipients-file <PATH>... Encrypt to the recipients listed at PATH. Can be repeated.
    \\-i, --identity <IDENTITY>...    Path to file of identities. Can be repeated.
    \\-p, --passphrase <PASSPHRASE>   Encrypt with a passphrase.
    \\-j <PLUGIN>                     Use age-plugin-PLUGIN as an identity
    \\-v, --version                   Print the version information and exit.
    \\-h, --help                      Print this help message and exit.
    \\<INPUT>                         Path of input file to read from (Default=stdin).
    \\
;

const parsers = .{
    .OUTPUT = clap.parsers.string,
    .RECIPIENT = clap.parsers.string,
    .PATH = clap.parsers.string,
    .IDENTITY = clap.parsers.string,
    .PASSPHRASE = clap.parsers.string,
    .PLUGIN = clap.parsers.string,
    .INPUT = clap.parsers.string,
};

const Args = struct {
    // encrypt or decrypt
    mode: enum {
        encrypt,
        decrypt,
    },
    // input file
    input: std.fs.File = std.fs.File.stdin(),
    // output file
    output: std.fs.File = std.fs.File.stdout(),
    // recipients - string? array of strings? or a custom data structure?
    recipients: []u8,
    // identities - string? array of strings? or a custom data structure?
    identities: []u8,
    // passphrase
    passphrase: []u8,
    // max work effort - u16 enough? more?
    max_work_effort: u16,
    // plugin - separate? or do we append it to our identities?
    // do we accept the plugin flag and the identities flag in one call?
    plugin: []u8,
};

pub fn main() !void {
    var args_alloc = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    const allocator = args_alloc.allocator();

    const params = comptime clap.parseParamsComptime(params_string);

    var diag = clap.Diagnostic{};
    const res = clap.parse(clap.Help, &params, parsers, .{
        .diagnostic = &diag,
        .allocator = allocator,
    }) catch |err| {
        try diag.reportToFile(.stderr(), err);
        return err;
    };

    if (res.args.help != 0) {
        var stdout_buffer: [params_string.len]u8 = undefined;
        var stdout_writer = std.fs.File.stdout().writer(&stdout_buffer);
        const stdout = &stdout_writer.interface;
        try stdout.print(usage_string, .{});
        try stdout.flush();
        args_alloc.deinit();
        return;
    }
    if (res.args.version != 0) {
        var stdout_buffer: [params_string.len]u8 = undefined;
        var stdout_writer = std.fs.File.stdout().writer(&stdout_buffer);
        const stdout = &stdout_writer.interface;
        try stdout.print("version: alpha neutron\n", .{});
        try stdout.flush();
        args_alloc.deinit();
        return;
    }

    if (res.args.encrypt != 0) {
        std.debug.print("encrypting...\n", .{});
    }
    if (res.args.decrypt != 0) {
        std.debug.print("decrypting...\n", .{});
    }
    if (res.args.output) |path| {
        std.debug.print("output: {s}\n", .{path});
    }
    for (res.args.recipient) |r| {
        std.debug.print("recipient: {s}\n", .{r});
    }
    for (res.args.@"recipients-file") |r| {
        std.debug.print("recipient file: {s}\n", .{r});
    }
    for (res.args.identity) |i| {
        std.debug.print("identity file: {s}\n", .{i});
    }
    if (res.args.passphrase) |p| {
        std.debug.print("passphrase: {s}\n", .{p});
    }
    if (res.args.j) |plugin| {
        std.debug.print("plugin: {s}\n", .{plugin});
    }
    if (res.positionals[0]) |input| {
        std.debug.print("input file path: {s}\n", .{input});
    }

    args_alloc.deinit();
}

test {
    std.testing.refAllDeclsRecursive(@This());
}
