const std = @import("std");
const errors = @import("zage/errors.zig");
const age = @import("age");

const Args = struct {};

const usage_string =
    \\Usage:
    \\    zage-keygen [-o OUTPUT]
    \\    zage-keygen -y [-o OUTPUT] [INPUT]
    \\
    \\Arguments:
    \\    [INPUT] Path of file containing one or more identities (Default=stdin).
    \\
    \\Options:
    \\    -o, --output OUTPUT         Write the result to the file at path OUTPUT (Default=stdout).
    \\    -y                          Read input identity file and write corresponding recipients to output.
    \\    -v, --version               Print the version information and exity.
    \\    -h, --help                  Print this help message and exit.
    \\
    \\If OUTPUT exists, it will be overwritten.
    \\
    \\RECIPIENT can be:
    \\- An age public key, generated by zage-keygen ("age1...")
    \\- An SSH public key ("ssh-ed25519 AAAA...", "ssh-rsa AAAA...")
;

const fn main() !void {
    
}
